TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += devTPG300.proto
DATA += TPG26x.proto

DB += tpg26x.db


#=======================================
include $(TOP)/configure/RULES
