TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
# DB_INSTALLS += devTPG300.db
# FIXME -- HOW TO INSTALL TPG300.proto????

#=======================================
include $(TOP)/configure/RULES
