TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += devTPG300.proto
DATA += TPG26x.proto

DB += devTPG300.db
DB += TPG300_channels.db
DB += unit_setter.db

DB += tpg26x.db


#=======================================
include $(TOP)/configure/RULES
