TOP=..
include $(TOP)/configure/CONFIG
#=======================================

# Install .dbd and .db files
DATA += devTPG300.proto

DB += devTPG300.db
DB += TPG300_channels.db
DB += unit_setter.db
DB += TPG300_switching_functions_rb.db
DB += TPG300_switching_functions.db

DB += tpg26x.db
DB += tpg36x.db
DATA += TPG26x.proto
DATA += TPG36x.proto


#=======================================
include $(TOP)/configure/RULES
